# dashboard_api.py  (v2 — adds /api/signals and /api/balance with assets)
import os, json, time, threading, logging, requests
from datetime import datetime, timezone
from pathlib import Path
from flask import Flask, jsonify, request, send_from_directory
from flask_cors import CORS
from dotenv import load_dotenv

load_dotenv(dotenv_path=".env", override=True)
app = Flask(__name__, static_folder="dashboard_static")
CORS(app)

TRADES_FILE  = "trades.json"
LOG_FILE     = "bot.log"
HISTORY_FILE = "trade_history.json"
SIGNALS_FILE = "signals.json"

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)


def load_json(path, default):
    try:
        if Path(path).exists():
            with open(path) as f: return json.load(f)
    except Exception: pass
    return default

def save_json(path, data):
    with open(path,"w") as f: json.dump(data, f, indent=2, default=str)

def get_live_prices(symbols):
    prices = {}
    try:
        for sym in symbols:
            try:
                # FIXED: Pointing to the Testnet API so Render doesn't get blocked
                r = requests.get("https://testnet.binance.vision/api/v3/ticker/price", params={"symbol": sym}, timeout=5)
                prices[sym] = float(r.json()["price"])
            except Exception: 
                prices[sym] = None
    except Exception: 
        pass
    return prices

def enrich_trades(trades, prices):
    result = []
    for sym, t in trades.items():
        entry = t.get("entry",0); qty = t.get("qty",0); signal = t.get("signal","BUY")
        live  = prices.get(sym)
        if live and entry and qty:
            upnl = round((live-entry)*qty if signal=="BUY" else (entry-live)*qty, 4)
            pct  = round((live-entry)/entry*100 if signal=="BUY" else (entry-live)/entry*100, 2)
        else:
            upnl, pct = 0, 0
        sl,tp1,tp2 = t.get("stop",0),t.get("tp1",0),t.get("tp2",0)
        dec = 4 if entry<10 else 2
        if signal=="BUY" and tp2>entry>sl:
            prog = round(max(0,min(100,(live-entry)/(tp2-entry)*100)),1) if live else 0
        elif signal=="SELL" and tp2<entry<sl:
            prog = round(max(0,min(100,(entry-live)/(entry-tp2)*100)),1) if live else 0
        else: prog = 0
        result.append({**t,"live_price":live,"unrealised_pnl":upnl,"pnl_pct":pct,
                        "progress":prog,"status":"TP1 hit" if t.get("tp1_hit") else "Open"})
    return result


@app.route("/api/status")
def api_status():
    trades  = load_json(TRADES_FILE, {})
    history = load_json(HISTORY_FILE, [])
    wins    = [h for h in history if (h.get("pnl",0) or 0) > 0]
    losses  = [h for h in history if (h.get("pnl",0) or 0) <= 0]
    total   = len(history)
    wr      = round(len(wins)/total*100, 1) if total else 0
    totpnl  = round(sum(h.get("pnl",0) or 0 for h in history), 4)
    return jsonify({"ok":True,"timestamp":datetime.now(timezone.utc).isoformat(),
                    "open_trades":len(trades),"max_trades":3,"total_closed":total,
                    "wins":len(wins),"losses":len(losses),"win_rate":wr,
                    "total_pnl":totpnl,"model_acc":73.1})


@app.route("/api/balance")
def api_balance():
    """Fetch testnet USDT balance + all asset holdings."""
    try:
        from trade_executor import init_exchange
        ex = init_exchange()
        b  = ex.fetch_balance()
        usdt = float(b.get("USDT",{}).get("free",0))
        assets = [
            {"asset": a, "free": str(b[a]["free"]), "total": str(b[a]["total"])}
            for a in b if isinstance(b[a], dict) and float(b[a].get("free",0) or 0) > 0
            and a not in ("info","free","used","total","timestamp","datetime")
        ]
        return jsonify({"ok":True,"usdt":usdt,"assets":assets,"other_count":len(assets)})
    except Exception as e:
        return jsonify({"ok":False,"usdt":None,"error":str(e)})


@app.route("/api/trades/open")
def api_open():
    trades  = load_json(TRADES_FILE, {})
    prices  = get_live_prices(list(trades.keys()))
    return jsonify(enrich_trades(trades, prices))


@app.route("/api/trades/history")
def api_history():
    return jsonify(load_json(HISTORY_FILE, [])[-100:])


@app.route("/api/signals")
def api_signals():
    """All signals generated by the bot (for Signals page)."""
    return jsonify(load_json(SIGNALS_FILE, [])[-200:])


@app.route("/api/log")
def api_log():
    try:
        if Path(LOG_FILE).exists():
            lines = Path(LOG_FILE).read_text().splitlines()
            return jsonify({"lines": lines[-150:]})
    except Exception: pass
    return jsonify({"lines": ["Log file not found"]})


@app.route("/api/scan", methods=["POST"])
def api_scan():
    def run():
        try:
            import subprocess
            subprocess.run(["python","trade_executor.py"], timeout=300)
        except Exception as e: log.error(f"Scan: {e}")
    threading.Thread(target=run, daemon=True).start()
    return jsonify({"ok":True,"message":"Scan started"})


@app.route("/api/close_trade", methods=["POST"])
@app.route("/api/close_trade", methods=["POST"])
def api_close():
    data   = request.get_json()
    symbol = data.get("symbol")
    if not symbol: return jsonify({"ok":False,"error":"symbol required"}), 400
    
    trades = load_json(TRADES_FILE, {})
    if symbol not in trades: return jsonify({"ok":False,"error":"Not found"}), 404
    
    try:
        from trade_executor import init_exchange
        ex    = init_exchange()
        trade = trades[symbol]
        
        # 1. Cancel the Stop Loss and Take Profit orders
        for oid in trade.get("order_ids",{}).values():
            try: ex.cancel_order(oid, symbol)
            except Exception: pass
            
        # 2. Execute the Market Close
        side = "sell" if trade["signal"]=="BUY" else "buy"
        order = ex.create_order(symbol, "market", side, trade["qty"])
        
        # 3. Safely calculate PnL using the actual filled price
        cp = float(order.get("average") or order.get("price") or trade["entry"])
        entry = float(trade["entry"])
        qty   = float(trade["qty"])
        
        pnl = round((cp - entry) * qty if trade["signal"] == "BUY" else (entry - cp) * qty, 4)
        
        # 4. Save to history
        history = load_json(HISTORY_FILE, [])
        history.append({
            **trade, 
            "close_price": cp, 
            "pnl": pnl,
            "closed_at": datetime.now(timezone.utc).isoformat(),
            "close_reason": "Manual close"
        })
        save_json(HISTORY_FILE, history)
        
        # 5. Remove from open trades
        trades.pop(symbol)
        save_json(TRADES_FILE, trades)
        
        return jsonify({"ok":True, "pnl":pnl})
        
    except Exception as e:
        return jsonify({"ok":False, "error":str(e)}), 500


@app.route("/")
def root():
    return send_from_directory("dashboard_static","index.html")

@app.route("/<path:path>")
def static_files(path):
    return send_from_directory("dashboard_static", path)


if __name__ == "__main__":
    port = int(os.getenv("PORT",5000))
    log.info(f"Dashboard API → http://localhost:{port}")
    app.run(host="0.0.0.0", port=port, debug=False)
